// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_microservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateUser
type CreateUserRequestV1 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequestV1) Reset()         { *m = CreateUserRequestV1{} }
func (m *CreateUserRequestV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequestV1) ProtoMessage()    {}
func (*CreateUserRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequestV1.Unmarshal(m, b)
}
func (m *CreateUserRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequestV1.Marshal(b, m, deterministic)
}
func (m *CreateUserRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequestV1.Merge(m, src)
}
func (m *CreateUserRequestV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequestV1.Size(m)
}
func (m *CreateUserRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequestV1 proto.InternalMessageInfo

func (m *CreateUserRequestV1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequestV1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequestV1) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequestV1) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateUserResponseV1 struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode           int64    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponseV1) Reset()         { *m = CreateUserResponseV1{} }
func (m *CreateUserResponseV1) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponseV1) ProtoMessage()    {}
func (*CreateUserResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponseV1.Unmarshal(m, b)
}
func (m *CreateUserResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponseV1.Marshal(b, m, deterministic)
}
func (m *CreateUserResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponseV1.Merge(m, src)
}
func (m *CreateUserResponseV1) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponseV1.Size(m)
}
func (m *CreateUserResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponseV1 proto.InternalMessageInfo

func (m *CreateUserResponseV1) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateUserResponseV1) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CreateUserResponseV1) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateUserResponseV1) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserResponseV1) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequestV1)(nil), "user_microservice.CreateUserRequestV1")
	proto.RegisterType((*CreateUserResponseV1)(nil), "user_microservice.CreateUserResponseV1")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0x4d, 0x6b, 0x1d, 0xbc, 0x38, 0x16, 0x59, 0x72, 0x10, 0xe9, 0x41, 0x3d, 0x45,
	0xa2, 0x47, 0x6f, 0xf6, 0x0d, 0x02, 0xe6, 0xe0, 0xa5, 0xac, 0xe9, 0x50, 0x02, 0x4d, 0x27, 0xce,
	0x6c, 0xf4, 0x55, 0x7c, 0x5c, 0xd9, 0x4d, 0xa2, 0x85, 0x08, 0xbd, 0xcd, 0x37, 0x93, 0xcc, 0xff,
	0xff, 0xb3, 0x00, 0xad, 0x92, 0xa4, 0x8d, 0xb0, 0x63, 0xbc, 0xf0, 0xf5, 0xba, 0xae, 0x4a, 0x61,
	0x25, 0xf9, 0xac, 0x4a, 0x5a, 0x32, 0x5c, 0xae, 0x84, 0xac, 0xa3, 0x57, 0x25, 0xc9, 0xe9, 0xa3,
	0x25, 0x75, 0x45, 0x86, 0x08, 0xf1, 0xde, 0xd6, 0x64, 0xa2, 0x9b, 0xe8, 0xfe, 0x2c, 0x0f, 0x35,
	0x2e, 0x60, 0x4a, 0xb5, 0xad, 0x76, 0xe6, 0x24, 0x34, 0x3b, 0xc0, 0x04, 0xe6, 0x8d, 0x55, 0xfd,
	0x62, 0xd9, 0x98, 0x49, 0x18, 0xfc, 0xb2, 0xdf, 0x22, 0xbc, 0x23, 0x13, 0x77, 0x5b, 0x7c, 0xbd,
	0xfc, 0x8e, 0x60, 0x71, 0xa8, 0xa8, 0x0d, 0xef, 0x95, 0x8a, 0x0c, 0x0d, 0x9c, 0x6a, 0x5b, 0x96,
	0xa4, 0x1a, 0x54, 0xe7, 0xf9, 0x80, 0x78, 0x0d, 0xa0, 0xce, 0xba, 0x56, 0x57, 0xbc, 0xa1, 0xa0,
	0x3e, 0xc9, 0x0f, 0x3a, 0x78, 0x05, 0xb3, 0x8e, 0x7a, 0x03, 0x3d, 0xf9, 0x8d, 0x35, 0xa9, 0xda,
	0xed, 0xe0, 0x60, 0xc0, 0x10, 0x45, 0x84, 0xc5, 0x4c, 0xfb, 0x28, 0x1e, 0x1e, 0xb7, 0x10, 0x7b,
	0x4f, 0xb8, 0x86, 0xf3, 0x3f, 0x87, 0x45, 0x86, 0xb7, 0xe9, 0xe8, 0x6e, 0xe9, 0x3f, 0x47, 0x4b,
	0xee, 0x8e, 0x7c, 0x37, 0x44, 0x7d, 0x49, 0xde, 0xcc, 0x43, 0x78, 0x91, 0xe7, 0xd1, 0x0f, 0xef,
	0xb3, 0x30, 0x78, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x1f, 0x67, 0x3e, 0xb8, 0x01, 0x00,
	0x00,
}
