// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_microservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateUser
type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode           int64    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateUserResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CreateUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user_microservice.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user_microservice.CreateUserResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc4, 0x40,
	0x0c, 0x86, 0xa9, 0xdb, 0x5d, 0xd7, 0xe0, 0x65, 0x83, 0xc8, 0xd0, 0x83, 0xc8, 0xa2, 0xe0, 0xa9,
	0xa2, 0x1e, 0xbd, 0xb9, 0x6f, 0x50, 0xd0, 0x83, 0x1e, 0x64, 0x9c, 0x0d, 0x52, 0xd8, 0xd9, 0xa9,
	0xc9, 0x54, 0xdf, 0xc4, 0xe7, 0x95, 0x49, 0x5b, 0x2d, 0xf4, 0xe0, 0x2d, 0xdf, 0x24, 0xfc, 0x7f,
	0xfe, 0x0c, 0x40, 0x2b, 0xc4, 0x65, 0xc3, 0x21, 0x06, 0x5c, 0xa5, 0xfa, 0xd5, 0xd7, 0x8e, 0x83,
	0x10, 0x7f, 0xd6, 0x8e, 0xd6, 0x1e, 0x56, 0x1b, 0x26, 0x1b, 0xe9, 0x51, 0x88, 0x2b, 0xfa, 0x68,
	0x49, 0x22, 0x22, 0xe4, 0x7b, 0xeb, 0xc9, 0x64, 0xe7, 0xd9, 0xd5, 0x51, 0xa5, 0x35, 0x9e, 0xc0,
	0x9c, 0xbc, 0xad, 0x77, 0xe6, 0x40, 0x1f, 0x3b, 0xc0, 0x02, 0x96, 0x8d, 0x15, 0xf9, 0x0a, 0xbc,
	0x35, 0x33, 0x6d, 0xfc, 0x72, 0x52, 0xe1, 0xb0, 0x23, 0x93, 0x77, 0x2a, 0xa9, 0x5e, 0x7f, 0x67,
	0x80, 0x63, 0x3f, 0x69, 0xc2, 0x5e, 0x08, 0x0d, 0x1c, 0x4a, 0xeb, 0x1c, 0x89, 0xa8, 0xe7, 0xb2,
	0x1a, 0x10, 0xcf, 0x00, 0x24, 0xda, 0xd8, 0xca, 0x26, 0x6c, 0x49, 0xbd, 0x67, 0xd5, 0xe8, 0x05,
	0x4f, 0x61, 0xd1, 0x51, 0x6f, 0xdf, 0x53, 0x52, 0xf4, 0x24, 0x62, 0xdf, 0x07, 0xff, 0x01, 0x35,
	0x08, 0x73, 0x60, 0x33, 0xef, 0x83, 0x24, 0xb8, 0x75, 0x90, 0xa7, 0x8d, 0xf0, 0x05, 0x8e, 0xff,
	0xf6, 0x7b, 0xba, 0xc1, 0x8b, 0x72, 0x72, 0xb3, 0x72, 0x72, 0xb0, 0xe2, 0xf2, 0x9f, 0xa9, 0x2e,
	0xe6, 0x43, 0xf1, 0x6c, 0xae, 0xf5, 0x27, 0xee, 0x27, 0xe3, 0x6f, 0x0b, 0x6d, 0xdc, 0xfd, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x3e, 0x58, 0xd0, 0x9c, 0xb0, 0x01, 0x00, 0x00,
}
