// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/uni-school/user-microservice/pkg/core/user/resource"
	"github.com/uni-school/user-microservice/pkg/core/user/service"
)

// Injectors from wire.go:

func UserService() service_user.IUserService {
	iUserResource := resource_user.InitUserResource()
	iUserService := service_user.InitUserService(iUserResource)
	return iUserService
}
